### ISSUE TITLE
webpack-cli error because of older version of dependency css-select

### ISSUE THREAD

**Issue by cetorres** [AriaMinaei/RenderKid#29]
I'm migrating my app from Node 14 to Node 16 and this errors now appears.

[webpack-cli] Failed to load '/app/webpack.config.js' config
[webpack-cli] TypeError: Cannot read properties of undefined (reading 'Descendant')
    at Object.<anonymous> (/app/node_modules/renderkid/node_modules/css-select/lib/compile.js:36:56)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/app/node_modules/renderkid/node_modules/css-select/lib/index.js:29:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:11[53]

I'm using this module on my app: `html-webpack-plugin` that has this dependency:
html-webpack-plugin@5.5.0
  └─┬ pretty-error@4.0.0
    └─┬ renderkid@3.0.0
      └── css-select@4.3.0

I believe `renderkid` is still using an older version of `css-select` 4.3.0 that is not compatible with Node 16. There is a newer version of [css-select](https://www.npmjs.com/package/css-select) 5.1.0 that is now updated and in TS that probably works with Node 16. Could you update `renderkid` to use this new version os `css-select`, please?

Thank you.

**Comment by Semigradsky** [comment]
@AriaMinaei please take a look

**Comment by askoufis** [comment]
@AriaMinaei Any chance this could be looked at? I'd also be happy to submit a PR, though my coffeescript understanding is practically non-existent, I don't think the breaking change in `css-select` v5 affects this package.
